// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogCard: typeof import('./components/ui/BlogCard.vue')['default']
    CareerCard: typeof import('./components/ui/CareerCard.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    FeaturedSection: typeof import('./components/slices/FeaturedSection.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HerosSection: typeof import('./components/slices/HerosSection.vue')['default']
    LineCharts: typeof import('./components/LineCharts.vue')['default']
    LoadingBlogCard: typeof import('./components/ui/LoadingBlogCard.vue')['default']
    LoadingBlogsCard: typeof import("./components/ui/LoadingBlogsCard.vue")["default"]
    LoadingProductCard: typeof import('./components/ui/LoadingProductCard.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    ProductCard: typeof import('./components/ui/ProductCard.vue')['default']
    ProductSection: typeof import('./components/slices/ProductSection.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
